---------/TABLE PERSONNE/-----------

CREATE TABLE "PERSONNE"(


DROP TABLE IF EXISTS "PERSONNE" CASCADE;

CREATE TYPE "SEXE" AS ENUM ('Feminin','Masculin');
CREATE TYPE "SITUATION_MATRIMONIALE" AS ENUM ('Célibataire','Mariée', 'Divorcée' ,'Veuve' );

CREATE TABLE "PERSONNE"
(

"ID_PERSONNE"   SERIAL NOT NULL ,
"NOM"           VARCHAR(100) NOT NULL,
"PRENOM"        VARCHAR(100) NOT NULL,
"DATE_NAISSANCE"  DATE NOT NULL,
"SEXE"            "SEXE",
"ADRESSE"         VARCHAR(50)NOT NULL,
"NATIONALITE"     VARCHAR(50) NOT NULL,
"PAYS_D_ORIGINE"   VARCHAR(50) NOT NULL,
"EMAIL"            VARCHAR(150) NOT NULL UNIQUE,
"PROFESSION"        VARCHAR(30) ,
"NOMBRE_ENFANT"     INTEGER ,
"NOM_CONJOINT"      VARCHAR(100) ,
"PRENOM_CONJOINT"   VARCHAR(100) ,
"AGE_CONJOINT"      VARCHAR (5),
"PROFESSION_CONJOINT" VARCHAR(30) ,

CONSTRAINT "PERSONNE_PK" PRIMARY KEY ("ID_PERSONNE"),
CONSTRAINT  "CHECK_DATE_NAISSANCE" CHECK ( "DATE_NAISSANCE" <=CURRENT_DATE AND "DATE_NAISSANCE">= '1900-01-01'


);