-- Création du schéma s'il n'existe pas
CREATE SCHEMA IF NOT EXISTS "MaterniteCare_Données";
SET SEARCH_PATH TO "maternite_care";



---------------/TABLE PERSONNE/---------------------

DROP TYPE IF EXISTS "SITUATION_MATRIMONIALE" CASCADE;
CREATE TYPE "SITUATION_MATRIMONIALE" AS ENUM ('Célibataire', 'Mariée', 'Divorcée', 'Veuve');
DROP TYPE IF EXISTS "SEXE" CASCADE;
CREATE TYPE "SEXE" AS ENUM ('Feminin', 'Masculin');

CREATE TABLE "PERSONNE" (
"ID_PERSONNE" SERIAL NOT NULL,
"NOM" VARCHAR(150) NOT NULL,
"PRENOM" VARCHAR(150) NOT NULL,
"DATE_NAISSANCE" DATE NOT NULL,
"SEXE" "SEXE",
"TEL" VARCHAR(12),
"ADRESSE" VARCHAR(50) NOT NULL,
"NATIONALITE" VARCHAR(50) NOT NULL,
"PAYS_D_ORIGINE" VARCHAR(50) NOT NULL,
"EMAIL" VARCHAR(150) NOT NULL UNIQUE,
"PROFESSION" VARCHAR(30),
"NOMBRE_ENFANT" INTEGER,
"NOM_CONJOINT" VARCHAR(100),
"PRENOM_CONJOINT" VARCHAR(100),
"AGE_CONJOINT" VARCHAR(5),
"PROFESSION_CONJOINT" VARCHAR(30),
"SITUATION_MATRIMONIALE" "SITUATION_MATRIMONIALE",
CONSTRAINT "PERSONNE_PK" PRIMARY KEY ("ID_PERSONNE"),
CONSTRAINT "CHECK_DATE_NAISSANCE" CHECK ("DATE_NAISSANCE" <= CURRENT_DATE AND "DATE_NAISSANCE" >= '1900-01-01')
);


--------------/TABLE TYPE_WORKSPACE/------------------


DROP TABLE IF EXISTS "TYPE_WORKSPACE" CASCADE;

CREATE TABLE "TYPE_WORKSPACE" (
"ID_TYPE_WORKSPACE" SERIAL NOT NULL,
"LIBELLE" TEXT NOT NULL UNIQUE,
 "DESCRIPTION" TEXT,
  CONSTRAINT "TYPE_WORKSPACE_PK" PRIMARY KEY ("ID_TYPE_WORKSPACE")
);

CREATE TYPE "SECTEUR" AS ENUM ('Secteur Consultations Prénatales','Bloc Obstétrical','Unité Post-Partum','Unité de Néonatalogie',
    'Service des Urgences Obstétricales',
    'Service d''Hospitalisation',
    'Secteur Administratif');

ALTER TABLE"TYPE_WORKSPACE" 
ADD COLUMN "SECTEUR" "SECTEUR";


-----------/TABLE TYPE_PERSONNEL/--------------------------
DROP TABLE IF EXISTS "TYPE_PERSONNEL" CASCADE;
CREATE TABLE "TYPE_PERSONNEL" (
"ID_TYPE_PERSONNEL" SERIAL NOT NULL,
"LIBELLE" TEXT NOT NULL,
"DESCRIPTION" TEXT,
CONSTRAINT "TYPE_PERSONNEL_PK" PRIMARY KEY ("ID_TYPE_PERSONNEL")
);

------------/ TABLE ROLE_PERSONNEL/-------------

DROP TABLE IF EXISTS "ROLE_PERSONNEL" CASCADE;
CREATE TABLE "ROLE_PERSONNEL" (
"ID_ROLE" SERIAL NOT NULL,
"LIBELLE" TEXT NOT NULL UNIQUE,
"DESCRIPTION" TEXT,
"NIVEAU_ACCES" INTEGER NOT NULL CHECK ("NIVEAU_ACCES" BETWEEN 1 AND 10),
CONSTRAINT "ROLE_ACCES_PK" PRIMARY KEY ("ID_ROLE")
);

----------/TABLE_SYMPTOME/---------------

DROP TYPE IF EXISTS "NIVEAU_SYMPTOME" CASCADE;
CREATE TYPE "NIVEAU_SYMPTOME" AS ENUM ('Faible', 'Modéré', 'Critique');
DROP TABLE IF EXISTS "SYMPTOME" CASCADE;
CREATE TABLE "SYMPTOME" (
"ID_SYMPTOME" SERIAL NOT NULL,
"NOM" VARCHAR(100) NOT NULL UNIQUE,
"DESCRIPTION" TEXT,
"NIVEAU_SYMPTOME" "NIVEAU_SYMPTOME" NOT NULL DEFAULT 'Modéré',
CONSTRAINT "SYMPTOME_PK" PRIMARY KEY ("ID_SYMPTOME")
);

------------/TABLE TYPE_GROSSESSE/---------------

DROP TABLE IF EXISTS "TYPE_GROSSESSE" CASCADE;
CREATE TABLE "TYPE_GROSSESSE" (
"ID_TYPE_GROSSESSE" SERIAL NOT NULL,
"LIBELLE" TEXT NOT NULL,
"DESCRIPTION" TEXT,
CONSTRAINT "TYPE_GROSSESSE_PK" PRIMARY KEY ("ID_TYPE_GROSSESSE")
);

-----------/ TABLE WORKSPACE/--------------

DROP TABLE IF EXISTS "WORKSPACE" CASCADE;
CREATE TABLE "WORKSPACE" (
"ID_WORKSPACE" SERIAL NOT NULL,
"NOM" VARCHAR(50) NOT NULL,
"NUMERO" INTEGER NOT NULL,
"CAPACITE" INTEGER NOT NULL,
"ID_TYPE_WORKSPACE" INTEGER NOT NULL,
CONSTRAINT "WORKSPACE_PKEY" PRIMARY KEY ("ID_WORKSPACE"),

CONSTRAINT "TYPE_WORKSPACE_FK" FOREIGN KEY ("ID_TYPE_WORKSPACE") 
REFERENCES "TYPE_WORKSPACE" ("ID_TYPE_WORKSPACE")
);

-----------/AJOUT STATUT_WORKSPACE/--------------
CREATE TYPE "STATUT_WORKSPACE" AS ENUM ('Disponible','Occupé','En maintenance');
ALTER TABLE "WORKSPACE"
ADD COLUMN "STATUT_WORKSPACE" "STATUT_WORKSPACE";




--------------/TABLE LITS /----------------

DROP TYPE IF EXISTS "STATUT_LIT" CASCADE;
CREATE TYPE "STATUT_LIT" AS ENUM ('Libre', 'Occupé', 'Nettoyage');
DROP TABLE IF EXISTS "LITS" CASCADE;
CREATE TABLE "LITS" (
"ID_LITS" SERIAL NOT NULL,
"NUMERO" INTEGER NOT NULL UNIQUE,
"LOCALISATION" VARCHAR(50),
"ID_WORKSPACE" INTEGER,
"STATUT" "STATUT_LIT" DEFAULT 'Libre',
CONSTRAINT "LITS_PK" PRIMARY KEY ("ID_LITS"),

CONSTRAINT "WORKSPACE_FK" FOREIGN KEY ("ID_WORKSPACE")
REFERENCES "WORKSPACE" ("ID_WORKSPACE")
);


-----------/TABLE PATIENTE/----------------

DROP TABLE IF EXISTS "PATIENTE" CASCADE;
CREATE TABLE "PATIENTE" (
"ID_PATIENTE" SERIAL NOT NULL,
"ID_PERSONNE" INTEGER NOT NULL, -- AJOUTÉ : Lien vers l'identité
"CODE_SUIVI" VARCHAR(10) NOT NULL UNIQUE,
"MATRICULE" VARCHAR(15) NOT NULL UNIQUE,
"GROUPE_SANGUIN" VARCHAR(5) NOT NULL,
"FACTEUR_RHESUS" VARCHAR(10),
"ANTECEDENT_MED" VARCHAR(255) NOT NULL,
"ANTECEDENT_FAMILIAL" VARCHAR(255) NOT NULL,
"ALLERGIE" VARCHAR(255) NOT NULL,
CONSTRAINT "PATIENTE_PK" PRIMARY KEY ("ID_PATIENTE"),

CONSTRAINT "PATIENTE_PERSONNE_FK" FOREIGN KEY ("ID_PERSONNE") 
REFERENCES "PERSONNE" ("ID_PERSONNE")
   
);


------------/TABLE PERSONNEL/---------------------

DROP TABLE IF EXISTS "PERSONNEL" CASCADE;
CREATE TABLE "PERSONNEL" (
"ID_PERSONNEL" SERIAL NOT NULL,
"ID_PERSONNE" INTEGER NOT NULL, -- AJOUTÉ : Lien vers l'identité
"MATRICULE" VARCHAR(15) NOT NULL UNIQUE,
"SPECIALITE" VARCHAR(50),
"DIPLOME" VARCHAR(50) NOT NULL,
"ID_TYPE_WORKSPACE" INTEGER NOT NULL,
"ID_TYPE_PERSONNEL" INTEGER NOT NULL,
"DEBUT_FONCTION" DATE,
"ETABLISSEMENT_DIPLOME" VARCHAR(50),
"ID_ROLE" INTEGER NOT NULL,
CONSTRAINT "PERSONNEL_PK" PRIMARY KEY ("ID_PERSONNEL"),

CONSTRAINT "PERSONNEL_PERSONNE_FK" FOREIGN KEY ("ID_PERSONNE")
REFERENCES "PERSONNE" ("ID_PERSONNE"),

CONSTRAINT "PERSONNEL_TYPE_WORKSPACE_FK" FOREIGN KEY ("ID_TYPE_WORKSPACE")
REFERENCES "TYPE_WORKSPACE" ("ID_TYPE_WORKSPACE"),

CONSTRAINT "PERSONNEL_TYPE_PERSONNEL_FK" FOREIGN KEY ("ID_TYPE_PERSONNEL")
REFERENCES "TYPE_PERSONNEL" ("ID_TYPE_PERSONNEL"),

CONSTRAINT "PERSONNEL_ROLE_FK" FOREIGN KEY ("ID_ROLE")
REFERENCES "ROLE_PERSONNEL" ("ID_ROLE")
    
);

------------------/TABLE GROSSESSE/-----------------------


DROP TYPE IF EXISTS "NIVEAU_RISQUE" CASCADE;
CREATE TYPE "NIVEAU_RISQUE" AS ENUM ('Eleve', 'Modere', 'Normal');
DROP TYPE IF EXISTS "TRIMESTRE" CASCADE;
CREATE TYPE "TRIMESTRE" AS ENUM ('1er', '2ème', '3ème', 'Post-Partum');
DROP TYPE IF EXISTS "STATUT_GROSSESSE" CASCADE;
CREATE TYPE "STATUT_GROSSESSE" AS ENUM ('En cours', 'Terminée', 'Compliquée');
DROP TABLE IF EXISTS "GROSSESSE" CASCADE;
CREATE TABLE "GROSSESSE" (
"ID_GROSSESSE" SERIAL NOT NULL,
"ID_PATIENTE" INTEGER NOT NULL,
"ID_TYPE_GROSSESSE" INTEGER NOT NULL,
"DATE_DEBUT" TIMESTAMP NOT NULL,
"DATE_ACCOUCHEMENT_PREVUE" DATE NOT NULL, -- Renommé pour clarté
"NOMBRE_GROSSESSE" INTEGER NOT NULL DEFAULT 1,
"TRIMESTRE" "TRIMESTRE",
"OBSERVATION" TEXT,
"STATUT_GROSSESSE" "STATUT_GROSSESSE" NOT NULL DEFAULT 'En cours',
"NIVEAU_RISQUE" "NIVEAU_RISQUE" NOT NULL DEFAULT 'Normal',
"NOMBRE_FOETUS" INTEGER NOT NULL DEFAULT 1 CHECK ("NOMBRE_FOETUS" BETWEEN 1 AND 4),
CONSTRAINT "GROSSESSE_PK" PRIMARY KEY ("ID_GROSSESSE"),

CONSTRAINT "GROSSESSE_PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE")
REFERENCES "PATIENTE" ("ID_PATIENTE"),
CONSTRAINT "GROSSESSE_TYPE_FK" FOREIGN KEY ("ID_TYPE_GROSSESSE")
REFERENCES "TYPE_GROSSESSE" ("ID_TYPE_GROSSESSE")
);
---------/TABLE CONSULTATION/---------------

DROP TABLE IF EXISTS "CONSULTATION" CASCADE;
CREATE TABLE "CONSULTATION" (
"ID_CONSULTATION" SERIAL NOT NULL,
"ID_PATIENTE" INTEGER NOT NULL,
"ID_GROSSESSE" INTEGER NOT NULL,
"ID_PERSONNEL" INTEGER NOT NULL,
"DATE_CONSULTATION" TIMESTAMP NOT NULL,
"MOTIF_CONSULTATION" TEXT,
"DIAGNOSTIC" VARCHAR(255),
CONSTRAINT "CONSULTATION_PK" PRIMARY KEY ("ID_CONSULTATION"),

CONSTRAINT "CONSULTATION_PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE") 
REFERENCES "PATIENTE" ("ID_PATIENTE"),
    
CONSTRAINT "CONSULTATION_GROSSESSE_FK" FOREIGN KEY ("ID_GROSSESSE") 
REFERENCES "GROSSESSE" ("ID_GROSSESSE"),
    
CONSTRAINT "CONSULTATION_PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL") 
REFERENCES "PERSONNEL" ("ID_PERSONNEL")
);

-----------/CONST_PHYSIOLOGIQUE/------------

DROP TABLE IF EXISTS "CONST_PHYSIOLOGIQUE" CASCADE;
CREATE TABLE "CONST_PHYSIOLOGIQUE" (
"ID_CONST_PHYSIO" SERIAL NOT NULL,
"ID_CONSULTATION" INTEGER NOT NULL,
"ID_PATIENTE" INTEGER NOT NULL,
"DATE_MESURE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"TENSION_ARTERIELLE" VARCHAR(20),
"POULS" INTEGER CHECK ("POULS" BETWEEN 30 AND 250),
"TEMPERATURE" DECIMAL(4,1) CHECK ("TEMPERATURE" BETWEEN 30.0 AND 45.0),
"TAILLE" DECIMAL(5,2) CHECK ("TAILLE" BETWEEN 50.0 AND 250.0),
"POIDS" DECIMAL(5,2) CHECK ("POIDS" BETWEEN 20.0 AND 200.0),
"FREQUENCE_CARDIAQUE" INTEGER CHECK ("FREQUENCE_CARDIAQUE" BETWEEN 30 AND 250),

CONSTRAINT "CONST_PHYSIO_PK" PRIMARY KEY ("ID_CONST_PHYSIO"),

CONSTRAINT "CONST_PHYSIO_CONSULTATION_FK" FOREIGN KEY ("ID_CONSULTATION") 
REFERENCES "CONSULTATION" ("ID_CONSULTATION"),
    
CONSTRAINT "CONST_PHYSIO_PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE") 
REFERENCES "PATIENTE" ("ID_PATIENTE")
);

---------/CONSULTATION/-----------------

DROP TABLE IF EXISTS "CONSULTATION_SYMPTOME" CASCADE;
CREATE TABLE "CONSULTATION_SYMPTOME" (
"ID_CONSULTATION" INTEGER NOT NULL,
"ID_SYMPTOME" INTEGER NOT NULL,
    
CONSTRAINT "CONSULTATION_SYMPTOME_PK" PRIMARY KEY ("ID_CONSULTATION", "ID_SYMPTOME"),
    
CONSTRAINT "CS_CONSULTATION_FK" FOREIGN KEY ("ID_CONSULTATION")
REFERENCES "CONSULTATION" ("ID_CONSULTATION"),
    
CONSTRAINT "CS_SYMPTOME_FK" FOREIGN KEY ("ID_SYMPTOME")
REFERENCES "SYMPTOME" ("ID_SYMPTOME")
);


----------/DOCUMENT/-----------------

DROP TYPE IF EXISTS "TYPE_DOCUMENT" CASCADE;
CREATE TYPE "TYPE_DOCUMENT" AS ENUM ('Echographie', 'Bilan sanguin', 'Ordonnance', 'Compte rendu', 'Autre');
DROP TABLE IF EXISTS "DOCUMENT" CASCADE;
CREATE TABLE "DOCUMENT" (
"ID_DOCUMENT" SERIAL NOT NULL,
"ID_PATIENTE" INTEGER NOT NULL,
"ID_PERSONNEL" INTEGER, 
 "TYPE_DOCUMENT" "TYPE_DOCUMENT" NOT NULL,
"NOM_DOCUMENT" VARCHAR(255) NOT NULL,
"CONTENU" TEXT,
"TYPE_MIME" VARCHAR(50) NOT NULL CHECK ("TYPE_MIME" IN ('image/jpeg', 'image/png', 'application/pdf')),
"DATE_DEPOT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"TAILLE" INTEGER CHECK ("TAILLE" > 0),
    
CONSTRAINT "DOCUMENT_PK" PRIMARY KEY ("ID_DOCUMENT"),
    
CONSTRAINT "DOCUMENT_PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE") 
REFERENCES "PATIENTE" ("ID_PATIENTE"),
   
CONSTRAINT "DOCUMENT_PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL") 
REFERENCES "PERSONNEL" ("ID_PERSONNEL")
);


------------------/ TABLE RENDEZ_VOUS/----------------


DROP TYPE IF EXISTS "STATUT_RDV" CASCADE;
CREATE TYPE "STATUT_RDV" AS ENUM ('Confirmé', 'Annulé', 'Effectué', 'Urgent');
DROP TABLE IF EXISTS "RENDEZ_VOUS" CASCADE;
CREATE TABLE "RENDEZ_VOUS" (
"ID_RENDEZ_VOUS" SERIAL NOT NULL,
"ID_PATIENTE" INTEGER NOT NULL,
"ID_PERSONNEL" INTEGER NOT NULL,
"DATE_RDV" TIMESTAMP NOT NULL,
"STATUT" "STATUT_RDV" NOT NULL DEFAULT 'Confirmé',
"MOTIF" VARCHAR(255),
 
 CONSTRAINT "RENDEZ_VOUS_PK" PRIMARY KEY ("ID_RENDEZ_VOUS"),
CONSTRAINT "RDV_PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE")
REFERENCES "PATIENTE" ("ID_PATIENTE"),
    
CONSTRAINT "RDV_PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL") 
REFERENCES "PERSONNEL" ("ID_PERSONNEL"),
CONSTRAINT "CHK_DATE_RDV" CHECK ("DATE_RDV" >= CURRENT_DATE)
);



----------------/TABLE ADMISSION/-------------------

DROP TYPE IF EXISTS "STATUT_ADMISSION" CASCADE;
CREATE TYPE "STATUT_ADMISSION" AS ENUM ('Actif', 'Observation', 'Stable');
DROP TYPE IF EXISTS "NIVEAU_URGENCE" CASCADE;
CREATE TYPE "NIVEAU_URGENCE" AS ENUM ('Elevé', 'Modéré', 'Normal');
CREATE TABLE "ADMISSION" (
"ID_ADMISSION" SERIAL NOT NULL,
"ID_PATIENTE" INTEGER NOT NULL,
"ID_GROSSESSE" INTEGER NOT NULL,
"ID_PERSONNEL" INTEGER NOT NULL,
"ID_WORKSPACE" INTEGER NOT NULL,
"ID_LITS" INTEGER NOT NULL,
"DATE_ADMISSION" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"DATE_SORTIE" TIMESTAMP, 
"MOTIF" TEXT NOT NULL,
"SERVICE" VARCHAR(50) NOT NULL,
"NIVEAU_URGENCE" "NIVEAU_URGENCE",
"STATUT_ADMISSION" "STATUT_ADMISSION" DEFAULT 'Actif',

CONSTRAINT "ADMISSION_PK" PRIMARY KEY ("ID_ADMISSION"),
    
CONSTRAINT "ADMISSION_PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE") 
REFERENCES "PATIENTE" ("ID_PATIENTE"),
    
CONSTRAINT "ADMISSION_GROSSESSE_FK" FOREIGN KEY ("ID_GROSSESSE") 
REFERENCES "GROSSESSE" ("ID_GROSSESSE"),
    
CONSTRAINT "ADMISSION_PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL") 
REFERENCES "PERSONNEL" ("ID_PERSONNEL"),
    
CONSTRAINT "ADMISSION_WORKSPACE_FK" FOREIGN KEY ("ID_WORKSPACE")
REFERENCES "WORKSPACE" ("ID_WORKSPACE"),
    
CONSTRAINT "ADMISSION_LITS_FK" FOREIGN KEY ("ID_LITS")
REFERENCES "LITS" ("ID_LITS")
);

-----------/ACCOUCHEMENT/-------------------

DROP TYPE IF EXISTS "TYPE_ACCOUCHEMENT" CASCADE;
CREATE TYPE "TYPE_ACCOUCHEMENT" AS ENUM ('Voie basse', 'Césarienne', 'Forceps');
DROP TABLE IF EXISTS "ACCOUCHEMENT" CASCADE;

CREATE TABLE "ACCOUCHEMENT" (
"ID_ACCOUCHEMENT" SERIAL NOT NULL,
"ID_PATIENTE" INTEGER NOT NULL,
"ID_PERSONNEL" INTEGER NOT NULL,
"ID_WORKSPACE" INTEGER ,
"DATE_ACCOUCHEMENT" TIMESTAMP NOT NULL,
"TYPE_ACCOUCHEMENT" "TYPE_ACCOUCHEMENT" NOT NULL,
"RESULTAT" VARCHAR(50) NOT NULL,
"POIDS_BEBE" DECIMAL(5,2) CHECK ("POIDS_BEBE" BETWEEN 0.3 AND 7.0),
"TAILLE_BEBE" DECIMAL(4,1) CHECK ("TAILLE_BEBE" BETWEEN 20.0 AND 70.0),
"NOMBRE_FAUSSE_COUCHES" INTEGER NOT NULL DEFAULT 0,
CONSTRAINT "ACCOUCHEMENT_PK" PRIMARY KEY ("ID_ACCOUCHEMENT"),
    
CONSTRAINT "ACCOUCHEMENT_PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE") 
REFERENCES "PATIENTE" ("ID_PATIENTE"),
    
CONSTRAINT "ACCOUCHEMENT_PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL")
REFERENCES "PERSONNEL" ("ID_PERSONNEL"),
    
CONSTRAINT "ACCOUCHEMENT_WORKSPACE_FK" FOREIGN KEY ("ID_WORKSPACE") 
REFERENCES "WORKSPACE" ("ID_WORKSPACE"),
    
CONSTRAINT "ACCOUCHEMENT_ADMISSION_FK" FOREIGN KEY ("ID_ADMISSION") 
REFERENCES "ADMISSION" ("ID_ADMISSION")
);
 



----------/TABLE NOUVEAU NES/-----------------------
DROP TYPE IF EXISTS "SEXE_BEBE" CASCADE;
CREATE TYPE "SEXE_BEBE" AS ENUM ('Fille', 'Garçon');
DROP TABLE IF EXISTS "NOUVEAU_NES" CASCADE;

CREATE TABLE "NOUVEAU_NES" (
    "ID_NOUVEAU_NES" SERIAL NOT NULL,
    "ID_PATIENTE" INTEGER NOT NULL,
    "ID_ACCOUCHEMENT" INTEGER NOT NULL,
    "NOM" VARCHAR(150) NOT NULL,
    "PRENOM" VARCHAR(150) NOT NULL,
    "DATE_NAISSANCE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SEXE" "SEXE_BEBE",
    "TAILLE" DECIMAL(4,1) CHECK ("TAILLE" BETWEEN 20.0 AND 70.0),
    "POIDS" DECIMAL(5,2) CHECK ("POIDS" BETWEEN 0.3 AND 7.0),
    "SCORE_APGAR_1MIN" INTEGER CHECK ("SCORE_APGAR_1MIN" BETWEEN 0 AND 10),
    "SCORE_APGAR_5MIN" INTEGER CHECK ("SCORE_APGAR_5MIN" BETWEEN 0 AND 10),
    "FACTEUR_RHESUS" VARCHAR(5) NOT NULL,
    "OBSERVATION" TEXT,
    CONSTRAINT "NOUVEAU_NES_PK" PRIMARY KEY ("ID_NOUVEAU_NES"),
    CONSTRAINT "NN_PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE") REFERENCES "PATIENTE" ("ID_PATIENTE"),
    CONSTRAINT "NN_ACCOUCHEMENT_FK" FOREIGN KEY ("ID_ACCOUCHEMENT") REFERENCES "ACCOUCHEMENT" ("ID_ACCOUCHEMENT")
);



----------TABLE AUDIT /-----------------------
DROP TYPE IF EXISTS "MODULE_AUDIT" CASCADE;
CREATE TYPE "MODULE_AUDIT" AS ENUM ('PATIENTE', 'ADMISSION', 'CONSULTATION', 'ACCOUCHEMENT', 'DOCUMENT', 'PERSONNEL', 'WORKSPACE', 'GROSSESSE', 'NOUVEAU_NES', 'VACCINATION', 'RENDEZ_VOUS');
DROP TYPE IF EXISTS "ACTION_AUDIT" CASCADE;
CREATE TYPE "ACTION_AUDIT" AS ENUM ('CREATION', 'MODIFICATION', 'SUPPRESSION', 'CONSULTATION', 'UPLOAD', 'CONNEXION', 'DECONNEXION');
DROP TABLE IF EXISTS "AUDIT" CASCADE;

CREATE TABLE "AUDIT" (
"ID_AUDIT" SERIAL NOT NULL,
"ID_PERSONNEL" INTEGER NOT NULL,
"ACTION_AUDIT" "ACTION_AUDIT" NOT NULL,
"MODULE" "MODULE_AUDIT" NOT NULL,
"TABLE_CONCERNEE" VARCHAR(50) NOT NULL,
"ENREGISTREMENT_ID" INTEGER,
"ANCIENNE_VALEUR" TEXT,
"NOUVELLE_VALEUR" TEXT,
"DATE_ACTION" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"ADRESSE_IP" VARCHAR(45),
CONSTRAINT "AUDIT_PK" PRIMARY KEY ("ID_AUDIT"),
CONSTRAINT "AUDIT_PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL") 
REFERENCES "PERSONNEL" ("ID_PERSONNEL")
);



--------------/ AJOUT DES DONNEES /-----------------

--------------/TYPE_WORKSPACE/-------------------------

INSERT INTO "TYPE_WORKSPACE" ( "LIBELLE", "DESCRIPTION" ,"SECTEUR")

VALUES('Consultations', 'échographies et examens de routine.', 'Secteur Consultations Prénatales'),
    ('Bloc','accouchements voie basse et césariennes.', 'Bloc Obstétrical'),
    ('Post-Partum', 'Chambres pour le séjour de la mère et du bébé après la naissance.', 'Unité Post-Partum'),
    ('Néonatologie', 'Prise en charge des nouveau-nés prématurés ou nécessitant des soins.', 'Unité de Néonatalogie'),
    ('Urgences', 'Prise en charge des urgences gynécologiques et obstétricales.', 'Service des Urgences Obstétricales');


-- --- ------------------/TYPE_PERSONNEL/--------------- ---
INSERT INTO "TYPE_PERSONNEL" ("LIBELLE", "DESCRIPTION") VALUES
('Médecin Gynécologue', 'Médecin spécialiste'),
('Sage-Femme', 'Professionnelle de la naissance'),
('Infirmière', 'Soins infirmiers'),
('Administratif', 'Secrétariat et accueil');

-- -----------------/ ROLE_PERSONNEL/-------------------- ---
INSERT INTO "ROLE_PERSONNEL" ("LIBELLE", "DESCRIPTION", "NIVEAU_ACCES") VALUES
('Administrateur', 'Accès total au système', 10),
('Médecin Chef', 'Gestion médicale et validation', 8),
('Médecin', 'Suivi patient et prescriptions', 7),
('Sage-Femme', 'Suivi accouchement et post-partum', 6),
('Secrétaire', 'Gestion des RDV et admissions', 4);

-- --- ---------------/TYPE_GROSSESSE/---------------- ---
INSERT INTO "TYPE_GROSSESSE" ("LIBELLE", "DESCRIPTION") VALUES
('Simple', 'Grossesse monofoetale sans complication'),
('Gémellaire', 'Grossesse de jumeaux'),
('À risque', 'Grossesse nécessitant une surveillance accrue');

-- ----------------- /SYMPTOME/ ---------------------
INSERT INTO "SYMPTOME" ("NOM", "DESCRIPTION", "NIVEAU_SYMPTOME") VALUES
('Nausées matinales', 'Envies de vomir fréquentes le matin', 'Faible'),
('Contractions', 'Resserrements utérins', 'Modéré'),
('Saignements', 'Pertes de sang vaginales', 'Critique'),
('Maux de tête', 'Céphalées persistantes', 'Modéré');

-- ------------- /WORKSPACE (Salles physiques)/ ---------------

INSERT INTO "WORKSPACE" ("NOM", "NUMERO", "CAPACITE", "ID_TYPE_WORKSPACE", "STATUT_WORKSPACE") VALUES
('Salle Consultation A', 1, 1, 1,'Disponible'),
('Salle Accouchement 1', 101, 1, 2,'Disponible'),
('Chambre Post-Partum 10', 201, 1, 3,'Occupé'),
('Couveuse Neo 1', 301, 1, 4,'Disponible'),
('Chambre Post-Partum 8', 202, 1, 4,'En maintenance');

-- --- LITS ---
INSERT INTO "LITS" ("NUMERO", "LOCALISATION", "ID_WORKSPACE", "STATUT") VALUES
(1, 'Salle Consultation A', 1, 'Libre'),
(101, 'Salle Accouchement 1', 2, 'Libre'),
(201, 'Chambre Post-Partum 10', 3, 'Libre'),
(301, 'Couveuse Neo 1', 4, 'Libre');

-- --- PERSONNE (Identité commune) ---

INSERT INTO "PERSONNE" ("NOM", "PRENOM", "DATE_NAISSANCE", "SEXE", "TEL", "ADRESSE", "NATIONALITE", "PAYS_D_ORIGINE", "EMAIL", "PROFESSION", "SITUATION_MATRIMONIALE") VALUES
('Dupont', 'Jean', '1975-05-12', 'Masculin', '0601020304', '10 rue de la Paix', 'Française', 'France', 'dr.dupont@maternite.com', 'Médecin', 'Mariée'),
('Martin', 'Sophie', '1985-08-20', 'Feminin', '0605060708', '5 avenue des Champs', 'Française', 'France', 'sf.martin@maternite.com', 'Sage-Femme', 'Célibataire');

INSERT INTO "PERSONNE" ("NOM", "PRENOM", "DATE_NAISSANCE", "SEXE", "TEL", "ADRESSE", "NATIONALITE", "PAYS_D_ORIGINE", "EMAIL", "PROFESSION", "SITUATION_MATRIMONIALE") VALUES
('Marie', 'Anne', '1983-10-2', 'Feminin', '0605067895', 'Paris', 'Française', 'France', 'dr.Marie@maternite.com', 'Médecin', 'Mariée');


-- Patientes
INSERT INTO "PERSONNE" ("NOM", "PRENOM", "DATE_NAISSANCE", "SEXE", "TEL", "ADRESSE", "NATIONALITE", "PAYS_D_ORIGINE", "EMAIL", "PROFESSION", "SITUATION_MATRIMONIALE") VALUES
('Dubois', 'Claire', '1992-03-15', 'Feminin', '0611121314', '20 rue de la Santé', 'Française', 'France', 'claire.dubois@email.com', 'Enseignante', 'Mariée'),
('Petit', 'Laura', '1988-11-02', 'Feminin', '0615161718', '8 boulevard Saint-Michel', 'Française', 'France', 'laura.petit@email.com', 'Architecte', 'Célibataire');


-- --- PERSONNEL (Lien Staff) ---

INSERT INTO "PERSONNEL" ("ID_PERSONNE", "MATRICULE", "SPECIALITE", "DIPLOME", "ID_TYPE_WORKSPACE", "ID_TYPE_PERSONNEL", "DEBUT_FONCTION", "ETABLISSEMENT_DIPLOME", "ID_ROLE") VALUES
(1, 'MAT-DOC-001', 'Gynécologie-Obstétrique', 'Doctorat Médecine', 1, 1, '2010-09-01', 'Université Paris Cité', 3);


INSERT INTO "PERSONNEL" ("ID_PERSONNE", "MATRICULE", "SPECIALITE", "DIPLOME", "ID_TYPE_WORKSPACE", "ID_TYPE_PERSONNEL", "DEBUT_FONCTION", "ETABLISSEMENT_DIPLOME", "ID_ROLE") VALUES
(2, 'MAT-SF-002', 'Maïeutique', 'Diplôme Sage-Femme', 2, 2, '2015-06-15', 'École de Sages-Femmes', 4);

INSERT INTO "PERSONNEL" ("ID_PERSONNE", "MATRICULE", "SPECIALITE", "DIPLOME", "ID_TYPE_WORKSPACE", "ID_TYPE_PERSONNEL", "DEBUT_FONCTION", "ETABLISSEMENT_DIPLOME", "ID_ROLE") VALUES
(3, 'MAT-SF-003', 'Gynécologie-Obstétrique', 'Doctorat Médecine', 3, 3, '2009-07-2', 'Université Londres', 2 );

-- --- PATIENTE (Lien Patientes) ---

INSERT INTO "PATIENTE" ("ID_PERSONNE", "CODE_SUIVI", "MATRICULE", "GROUPE_SANGUIN", "FACTEUR_RHESUS", "ANTECEDENT_MED", "ANTECEDENT_FAMILIAL", "ALLERGIE") VALUES
(3, 'SUIVI-001', 'PAT-2023-001', 'O+', 'Positif', 'Aucun', 'Diabète type 2 (mère)', 'Pénicilline');

-- Laura Petit (ID_PERSONNE = 4)
INSERT INTO "PATIENTE" ("ID_PERSONNE", "CODE_SUIVI", "MATRICULE", "GROUPE_SANGUIN", "FACTEUR_RHESUS", "ANTECEDENT_MED", "ANTECEDENT_FAMILIAL", "ALLERGIE") VALUES
(4, 'SUIVI-002', 'PAT-2023-002', 'A-', 'Négatif', 'Asthme', 'Aucun', 'Aucune');


-- --- GROSSESSE ---

-- Claire Dubois (ID_PATIENTE = 1) a une grossesse simple

INSERT INTO "GROSSESSE" ("ID_PATIENTE", "ID_TYPE_GROSSESSE", "DATE_DEBUT", "DATE_ACCOUCHEMENT_PREVUE", "NOMBRE_GROSSESSE", "TRIMESTRE", "STATUT_GROSSESSE", "NIVEAU_RISQUE", "NOMBRE_FOETUS") VALUES
(1, 1, '2023-10-01 00:00:00', '2024-07-08', 1, '2ème', 'En cours', 'Normal', 1);

-- --- RENDEZ_VOUS ---
-- Claire a un RDV avec Dr. Dupont

INSERT INTO "RENDEZ_VOUS" ("ID_PATIENTE", "ID_PERSONNEL", "DATE_RDV", "STATUT", "MOTIF") VALUES
(1, 1, '2026-07-15 10:00:00', 'Confirmé', 'Consultation de routine 2ème trimestre');

-- --- CONSULTATION ---


-- La consultation a eu lieu
INSERT INTO "CONSULTATION" ("ID_PATIENTE", "ID_GROSSESSE", "ID_PERSONNEL", "DATE_CONSULTATION", "MOTIF_CONSULTATION", "DIAGNOSTIC") VALUES
(1, 1, 1, '2026-08-10 10:00:00', 'Suivi grossesse', 'Grossesse évolutive, bien-être fœtal satisfaisant');


-- --- CONST_PHYSIOLOGIQUE (Pour cette consultation) ---
INSERT INTO "CONST_PHYSIOLOGIQUE" ("ID_CONSULTATION", "ID_PATIENTE", "DATE_MESURE", "TENSION_ARTERIELLE", "POULS", "TEMPERATURE", "TAILLE", "POIDS", "FREQUENCE_CARDIAQUE") VALUES
(1, 1, '2026-08-10 10:05:00', '120/80', 75, 37.2, 165.00, 62.50, 140);

-- --- CONSULTATION_SYMPTOME ---

-- Claire a eu des nausées lors de cette consultation
INSERT INTO "CONSULTATION_SYMPTOME" ("ID_CONSULTATION", "ID_SYMPTOME") VALUES (1, 1);

-- --- ADMISSION ---
-- Claire est admise pour accouchement
INSERT INTO "ADMISSION " ("ID_PATIENTE ", "ID_GROSSESSE ", "ID_PERSONNEL ", "ID_WORKSPACE ", "ID_LITS ", "DATE_ADMISSION ", "MOTIF ", "SERVICE ", "NIVEAU_URGENCE ", "STATUT_ADMISSION ") VALUES
(1, 1, 2, 2, 101, '2024-07-08 08:30:00', 'Début de travail', 'Bloc Obstétrical', 'Normal', 'Actif');


-- --- ACCOUCHEMENT ---

INSERT INTO "ACCOUCHEMENT" ("ID_PATIENTE", "ID_PERSONNEL", "ID_WORKSPACE", "DATE_ACCOUCHEMENT", "TYPE_ACCOUCHEMENT", "RESULTAT", "POIDS_BEBE", "TAILLE_BEBE", "NOMBRE_FAUSSE_COUCHES") VALUES
(1, 1, 2, '2026-07-08 14:15:00', 'Voie basse', 'Vivant', 3.25, 50.0, 0);

-- --- NOUVEAU_NES ---
-- Bébé de Claire (ID_PATIENTE=1, ID_ACCOUCHEMENT=1)

INSERT INTO "NOUVEAU_NES" ("ID_PATIENTE", "ID_ACCOUCHEMENT", "NOM", "PRENOM", "DATE_NAISSANCE", "SEXE", "TAILLE", "POIDS", "SCORE_APGAR_1MIN", "SCORE_APGAR_5MIN", "FACTEUR_RHESUS", "OBSERVATION") VALUES
(1, 1, 'Dubois', 'Lucas', '2026-07-08 14:15:00', 'Garçon', 50.0, 3.25, 9, 10, 'Positif', 'Bébé en bonne santé, pas de complication');
