
--/Pour définir le shéma à utilisé/--

SET SEARCH_PATH TO"MaterniteCare_Données";

--/CREATION DES DIFFERENTES TABLES /--

-------------/TABLE_PERSONNE/--------------------------

DROP TABLE IF EXISTS "PERSONNE" CASCADE;

CREATE TYPE "SEXE" AS ENUM ('Feminin','Masculin');
CREATE TYPE "SITUATION_MATRIMONIALE" AS ENUM ('Célibataire','Mariée', 'Divorcée' ,'Veuve' );

CREATE TABLE "PERSONNE"
(

"ID_PERSONNE"   SERIAL NOT NULL ,
"NOM"           VARCHAR(150) NOT NULL,
"PRENOM"        VARCHAR(150) NOT NULL,
"DATE_NAISSANCE"  DATE NOT NULL,
"SEXE"            "SEXE",
"TEL"             VARCHAR(12),
"ADRESSE"         VARCHAR(50)NOT NULL,
"NATIONALITE"     VARCHAR(50) NOT NULL,
"PAYS_D_ORIGINE"   VARCHAR(50) NOT NULL,
"EMAIL"            VARCHAR(150) NOT NULL UNIQUE,
"PROFESSION"        VARCHAR(30) ,
"NOMBRE_ENFANT"     INTEGER ,
"NOM_CONJOINT"      VARCHAR(100) ,
"PRENOM_CONJOINT"   VARCHAR(100) ,
"AGE_CONJOINT"      VARCHAR (5),
"PROFESSION_CONJOINT" VARCHAR(30) ,
"SITUATION_MATRIMONIALE" "SITUATION_MATRIMONIALE" ,


CONSTRAINT "PERSONNE_PK" PRIMARY KEY ("ID_PERSONNE"),
CONSTRAINT  "CHECK_DATE_NAISSANCE" CHECK ( "DATE_NAISSANCE" <=CURRENT_DATE AND "DATE_NAISSANCE">= '1900-01-01')
);


---------------/TABLE_WORKSPACE/-------------------------

DROP TABLE IF EXISTS "WORKSPACE" CASCADE;
CREATE TABLE "WORKSPACE" 
(

"ID_WORKSPACE"  SERIAL NOT NULL,
"NOM"          VARCHAR (50) NOT NULL,
"NUMERO"      INTEGER NOT NULL,
"CAPACITE"    INTEGER NOT NULL,
"ID_TYPE_WORKSPACE" INTEGER NOT NULL ,

CONSTRAINT "WORKSPACE_PKEY" PRIMARY KEY ("ID_WORKSPACE"),
CONSTRAINT "TYPE_WORKSPACE_FK" FOREIGN KEY ("ID_TYPE_WORKSPACE")
REFERENCES "TYPE_WORKSPACE" ("ID_TYPE_WORKSPACE")

);

----------------/TABLE_TYPE_WORKSPACE/------------------------

CREATE TABLE "TYPE_WORKSPACE" (

"ID_TYPE_WORKSPACE"  SERIAL NOT NULL,
"LIBELLE"            TEXT NOT NULL UNIQUE,
"DESCRIPTION"        TEXT  ,
"ID_WORKSPACE"        INTEGER,

CONSTRAINT "TYPE_WORKSPACE_PK" PRIMARY KEY ("ID_TYPE_WORKSPACE" )

);

-------------------/TABLE LITS/-------------------------

CREATE TYPE "STATUT" AS ENUM ('Libre','Occupé','Nettoyage');
CREATE TABLE "LITS" (

"ID_LITS" SERIAL NOT NULL,
"NUMERO" INTEGER NOT NULL UNIQUE,
"LOCALISATION" VARCHAR (50),
"ID_WORKSPACE" INTEGER ,
"STATUT" "STATUT",

CONSTRAINT "LITS_PK" PRIMARY KEY ("ID_LITS"),
CONSTRAINT "WORKSPACE_FK" FOREIGN KEY ("ID_WORKSPACE")
REFERENCES "WORKSPACE" ("ID_WORKSPACE")

);

-------------------/TABLE TYPE_PERSONNEL/--------------------
DROP TABLE IF EXISTS "TYPE_PERSONNEL" CASCADE;
CREATE TABLE "TYPE_PERSONNEL"(

"ID_TYPE_PERSONNEL" SERIAL NOT NULL,
"LIBELLE" TEXT NOT NULL,
"DESCRIPTION" TEXT ,

CONSTRAINT "TYPE_PERSONNEL_PK" PRIMARY KEY ("ID_TYPE_PERSONNEL")

);

-----------------/ TABLE ROLE_PERSONNEL/------------------

DROP TABLE IF EXISTS "ROLE_PERSONNEL" CASCADE;

CREATE TABLE "ROLE_PERSONNEL"(

"ID_ROLE" SERIAL NOT NULL,
"LIBELLE" TEXT NOT NULL UNIQUE,
"DESCRIPTION" TEXT ,
"NIVEAU_ACCES" INTEGER NOT NULL CHECK ("NIVEAU_ACCES" BETWEEN 1 AND 10),

CONSTRAINT "ROLE_ACCES_PK" PRIMARY KEY ("ID_ROLE")
);




--------------------/ TABLE AUDIT/--------------------


CREATE TYPE "ACTION_AUDIT" AS ENUM ('CREATION','MODIFICATION','SUPPRESSION','CONSULTATION','UPLOAD','CONNEXION','DECONNEXION');


CREATE TYPE "MODULE_AUDIT" AS ENUM ( 'PATIENTE', 'ADMISSION', 'CONSULTATION','ACCOUCHEMENT','DOCUMENT','PERSONNEL','WORKSPACE',
    'GROSSESSE',
    'NOUVEAU_NES',
    'VACCINATION',
    'RENDEZ_VOUS');

CREATE TABLE "AUDIT" (

"ID_AUDIT"           SERIAL          NOT NULL,
"ACTION_AUDIT"             "ACTION_AUDIT"  NOT NULL,
"MODULE"             "MODULE_AUDIT"  NOT NULL,
"TABLE_CONCERNEE"    VARCHAR(50)     NOT NULL,
"ENREGISTREMENT"  INTEGER,
"ANCIENNE_VALEUR"    TEXT,
"NOUVELLE_VALEUR"    TEXT,
"DATE_ACTION"        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
"ADRESSE_IP"         VARCHAR(45),
   
"ID_PERSONNEL"       INTEGER         NOT NULL,

CONSTRAINT "AUDIT_PK" PRIMARY KEY ("ID_AUDIT"),
CONSTRAINT "PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL")
REFERENCES "PERSONNEL" ("ID_PERSONNEL")
);


--------------/TABLE ADMISSION/--------------------



CREATE TYPE "NIVEAU_URGENCE" AS ENUM ('Elevé', 'Modéré', 'Normal');
CREATE TYPE "STATUT_ADMISION" AS ENUM ('Actif','Observation','Stable');

CREATE TABLE "ADMISSION"(
"ID_ADMISSION" SERIAL NOT NULL,
"DATE_ADMISSION" DATE NOT NULL,
"MOTIF" TEXT NOT NULL,
"SERVICE" VARCHAR (50) NOT NULL,
"NIVEAU_URGENCE" "NIVEAU_URGENCE",
"DATE_SORTIE" TIMESTAMP NOT NULL,
"ID_PATIENTE" INTEGER  NOT NULL,
"ID_PERSONNEL" INTEGER NOT NULL,
"ID_GROSSESSE" INTEGER NOT NULL,
"ID_WORKSPACE" INTEGER NOT NULL,
"ID_LITS" INTEGER NOT NULL,

CONSTRAINT "ADMISSION_PK" PRIMARY KEY ("ID_ADMISSION"),


CONSTRAINT "WORKSAPCE_FK" FOREIGN KEY ("ID_WORKSPACE")
REFERENCES "WORKSPACE" ("ID_WORKSPACE"),

CONSTRAINT "GROSSESSE_FK" FOREIGN KEY ("ID_GROSSESSE")
REFERENCES "GROSSESSE" ("ID_GROSSESSE"),
CONSTRAINT "LITS_FK" FOREIGN KEY ("ID_LITS")
REFERENCES "LITS" ("ID_LITS"),
CONSTRAINT "PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL")
REFERENCES "PERSONNEL" ("ID_PERSONNEL")

);

              ---------/MODIFICATION:AJOUT ID_PATIENTE_FK DANS ADMISSION /---------------

ALTER TABLE "ADMISSION"
ADD CONSTRAINT "ADMISSION_PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE")
REFERENCES "PATIENTE" ("ID_PATIENTE");

                   --------------------/ TABLE ACCOUCHEMENT/--------------------------


CREATE TYPE "TYPE_ACCOUCHEMENT" AS ENUM ('Vois basse','Césarienne','Forceps');
CREATE TYPE "SEXE_BEBE" AS ENUM ('Fille', 'Garçon');

CREATE TABLE "ACCOUCHEMENT"(

"ID_ACCOUCHEMENT"   SERIAL NOT NULL,
"DATE_ACCOUCHEMENT"  TIMESTAMP NOT NULL,
"NOMBRE_ACCOUCHEMENT" INTEGER NOT NULL,
"RESULTAT" VARCHAR (50) NOT NULL,
"POIDS_BEBE" DECIMAL (5,2) CHECK ("POIDS_BEBE" BETWEEN 0.3 AND 7),
"TAILLE_BEBE" DECIMAL (4,1)CHECK ("TAILLE_BEBE" BETWEEN 20 AND 70),
"ID_PERSONNEL" INTEGER NOT NULL,
"ID_WORKSPACE" INTEGER NOT NULL,
"ID_PATIENTE" INTEGER NOT NULL,
"NOMBRE_FAUSSE_COUCHE" INTEGER NOT NULL,

CONSTRAINT "ACCOUCHEMENT_PK" PRIMARY KEY ("ID_ACCOUCHEMENT"),
CONSTRAINT "PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL")
REFERENCES "PERSONNEL" ("ID_PERSONNEL"),

CONSTRAINT "WORKSPACE_FK" FOREIGN KEY ("ID_WORKSPACE")
REFERENCES "WORKSPACE" ("ID_WORKSPACE")


);

            -----------------/MODIFICATION:AJOUT ID_PATIENTE_FK DANS ACCOUCHEMENT/-----------

ALTER TABLE "ACCOUCHEMENT"
ADD CONSTRAINT "ACCOUCHEMENT_PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE")
REFERENCES "PATIENTE" ("ID_PATIENTE");


                  ---------------------/TABLE PATIENTE/----------------------

DROP TABLE IF EXISTS "PATIENTE" CASCADE;
CREATE TABLE "PATIENTE"(

"ID_PATIENTE" SERIAL NOT NULL,
"CODE_SUVI" VARCHAR (10) NOT NULL UNIQUE ,
"MATRICULE" VARCHAR(15) NOT NULL UNIQUE,
"GROUPE_SANGUIN" VARCHAR(5) NOT NULL,
"FACTEUR_RHESUS" VARCHAR (10),
"CONST_PSYSIOLOGIQUE" VARCHAR(50)NOT NULL,
"ANTECEDENT_MED" VARCHAR(50) NOT NULL,
"ANTECEDENT_FAMILIALE" VARCHAR(50)NOT NULL,
"ALLERGIE" VARCHAR(50) NOT NULL,
"ID_CONSULTATION" INTEGER NOT NULL,
"ID_NOUVEAU_NES"INTEGER NOT NULL,
"ID_ADMISSION"INTEGER NOT NULL,

CONSTRAINT "PATIENTE_PK" PRIMARY KEY ("ID_PATIENTE"),
CONSTRAINT "CONSULTATION_FK"FOREIGN KEY("ID_CONSULTATION")
REFERENCES "CONSULTATION" ("ID_CONSULTATION"),

CONSTRAINT "NOUVEAU_NES_FK" FOREIGN KEY ("ID_NOUVEAU_NES")
REFERENCES "NOUVEAU_NES" ("ID_NOUVEAU_NES"),

CONSTRAINT "ADMISSION_FK" FOREIGN KEY ("ID_ADMISSION")
REFERENCES "ADMISSION" ("ID_ADMISSION")

);

                   -------------------/TABLE NOUVEAU_NES/--------------------

DROP TABLE IF EXISTS "NOUVEAU_NES" CASCADE;
CREATE TABLE "NOUVEAU_NES"(

"ID_NOUVEAU_NES" SERIAL NOT NULL,
"NOM" VARCHAR (150) NOT NULL,
"PRENOM" VARCHAR (150) NOT NULL,
"DATE_NAISSANCE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
"TAILLE" DECIMAL (4,1) CHECK("TAILLE" BETWEEN 20 AND 70),
"POIDS" DECIMAL (5,2) CHECK ("POIDS" BETWEEN 0.3 AND 7),
"SCORE_APGAR_1MIN" INTEGER CHECK ("SCORE_APGAR_1MIN" BETWEEN 0 AND 10),
"SCORE_APGAR_5MIN" INTEGER CHECK ("SCORE_APGAR_5MIN" BETWEEN 0 AND 10),
"ANTECEDENT_MED" TEXT ,
"SEXE" "SEXE",
"HEURE_NAISSANCE" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"FACTEUR_RHESUS" VARCHAR (5) NOT NULL,
"ID_PATIENTE" INTEGER NOT NULL,
"ID_ACCOUCHEMENT" INTEGER NOT NULL,

CONSTRAINT "NOUVEAU_NES_PK" PRIMARY KEY ("ID_NOUVEAU_NES"),


CONSTRAINT "ACCOUCHEMENT_FK" FOREIGN KEY ("ID_ACCOUCHEMENT")
REFERENCES "ACCOUCHEMENT" ("ID_ACCOUCHEMENT")

);

          -------------/MODIFICATION:AJOUT DE ID_PATIENTE_FK DANS NOUVEAU_NES/------------

ALTER TABLE "NOUVEAU_NES"
ADD CONSTRAINT "NOUVEAU_NES_PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE")
REFERENCES "PATIENTE" ("ID_PATIENTE");

                 --------------------/TABLE GROSSESSE/----------------------


CREATE TYPE "TRIMESTRE" AS ENUM ('1er','2er','3er','Post-Partum') ;
CREATE TYPE "STATUT_GROSSESSE" AS ENUM ( 'En cours', 'Terminée', 'Compliquée');

CREATE TYPE "NIVEAU_RISQUE" AS ENUM ( 'Eleve','Modere',  'Normal');   
CREATE TABLE "GROSSESSE"(
"ID_GROSSESSE" SERIAL NOT NULL,
"DATE_DEBUT" TIMESTAMP NOT NULL,
"DATE_ACCOUCHEMENT" DATE NOT NULL,
"NOMBRE_GROSSESSE" INTEGER NOT NULL DEFAULT 1,
"TRIMESTRE" "TRIMESTRE",
"OBSERVATION" TEXT,
"STATUT_GROSSESSE" "STATUT_GROSSESSE" NOT NULL DEFAULT 'En cours', 
"NIVEAU_RISQUE" "NIVEAU_RISQUE" NOT NULL DEFAULT 'Normal',
"NOMBRE_FOETUS" INTEGER NOT NULL DEFAULT 1 CHECK ("NOMBRE_FOETUS" BETWEEN 1 AND 4),
"ID_PATIENTE" INTEGER NOT NULL,
"ID_TYPE_GROSSESSE" INTEGER NOT NULL,

CONSTRAINT "GROSSESSE_PK" PRIMARY KEY ("ID_GROSSESSE"),


CONSTRAINT "TYPE_GROSSESSE_FK" FOREIGN KEY ("ID_TYPE_GROSSESSE")
REFERENCES "TYPE_GROSSESSE" ("ID_TYPE_GROSSESSE")

);

           -------/MODIFICATION:AJOUT DE ID_PATIENTE_FK DANS GROSSESSE/---------------------

ALTER TABLE "GROSSESSE"
ADD CONSTRAINT "PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE")
 REFERENCES "PATIENTE" ("ID_PATIENTE");

                -------------/ TABLE TYPE_GROSSESSE/--------------

DROP TABLE IF EXISTS "TYPE_GROSSESSE" CASCADE;
CREATE TABLE "TYPE_GROSSESSE"(
"ID_TYPE_GROSSESSE" SERIAL NOT NULL,
"LIBELLE" TEXT NOT NULL,
"DESCRIPTION" TEXT ,

CONSTRAINT "TYPE_GROSSESSE_PK" PRIMARY KEY ("ID_TYPE_GROSSESSE")

);


            -----------------/ TABLE CONSULTATION/-----------------------

CREATE TABLE "CONSULTATION"(
"ID_CONSULTATION" SERIAL NOT NULL,
"DATE_CONSULTATION" TIMESTAMP NOT NULL,
"MOTIF_CONSULTATION" TEXT ,
"DIAGNOSTIC" VARCHAR (255),
"ID_PERSONNEL" INTEGER NOT NULL,
"ID_GROSSESSE" INTEGER NOT NULL,
"ID_PATIENTE" INTEGER NOT NULL,

CONSTRAINT "CONSULTAION_PK" PRIMARY KEY ("ID_CONSULTATION"),
CONSTRAINT "PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL")
REFERENCES "PERSONNEL" ("ID_PERSONNEL"),

CONSTRAINT "GROSSESSE_FK" FOREIGN KEY ("ID_GROSSESSE")
REFERENCES "GROSSESSE" ("ID_GROSSESSE")

);

                ------------/MODIFICATION:AJOUT DE ID_PATIENTE_FK DANS CONSULTATION/---------------

ALTER TABLE "CONSULTATION"
ADD CONSTRAINT "PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE")
REFERENCES "PATIENTE" ("ID_PATIENTE");

          -------------------/TABLE_PERSONNEL/---------------------------------


CREATE TYPE "FONCTION" AS ENUM ('Gynécologue', 'Sage-Femme','Obstétricien','Infirmier', 'Pédiatre','Administration');
CREATE TYPE "SPECIALITE" AS ENUM ( 'Obstétrique', 'Néonatologie', 'Maïeutique',
    'Anesthésie',
    'Pédiatrie',
    'Soins Infirmiers',
    'Gestion Hospitalière'
);

 CREATE TABLE "PERSONNEL"
(
"ID_PERSONNEL"  SERIAL NOT NULL,
"MATRICULE"     VARCHAR(15) NOT NULL UNIQUE,
"SPECIALITE"    VARCHAR (50),
"DIPLOME"        VARCHAR (50) NOT NULL ,
"ID_TYPE_WORKSPACE" INTEGER NOT NULL ,
"ID_TYPE_PERSONNEL" INTEGER NOT NULL ,
"DEBUT_FONCTION"    DATE ,
"ETABLISSEMENT_DIPLOME" VARCHAR (50),
"ID_ROLE"    INTEGER NOT NULL ,
"ID_ADMISSION" INTEGER NOT NULL,


CONSTRAINT "PERSONNEL_PK" PRIMARY KEY ("ID_PERSONNEL"),
CONSTRAINT "PERSONNEL_TYPE_WORSPACE_FKEY" FOREIGN KEY ("ID_TYPE_WORKSPACE")
REFERENCES "TYPE_WORKSPACE" ("ID_TYPE_WORKSPACE"),

CONSTRAINT "PERSONNEL_TYPE_PERSONNEL_FKEY" FOREIGN KEY ("ID_TYPE_PERSONNEL")
REFERENCES "TYPE_PERSONNEL" ("ID_TYPE_PERSONNEL"),

CONSTRAINT "PERSONNEL_ROLE_FKEY" FOREIGN KEY ("ID_ROLE")
REFERENCES "ROLE_PERSONNEL" ("ID_ROLE")
);



          -----------/MODIFICATION:AJOUT DE ID_ADMISSION_FK DANS PERSONNEL/---------------
ALTER TABLE "PERSONNEL"
ADD CONSTRAINT "ADMISSION_FK" FOREIGN KEY ("ID_ADMISSION")
REFERENCES "ADMISSION" ("ID_ADMISSION");

               -------------/TABLE RENDEZ_VOUS/--------------------

CREATE TYPE "STATUT_RDV" AS ENUM ('Confirmé','Annulé','Effectué','Urgent');

CREATE TABLE "RENDEZ_VOUS" (
"ID_RENDEZ_VOUS" SERIAL        NOT NULL,
"DATE_RDV"       TIMESTAMP     NOT NULL,
"STATUT"         "STATUT_RDV"  NOT NULL DEFAULT 'Confirmé',
"MOTIF"          VARCHAR(255),
  
"ID_PATIENTE"    INTEGER       NOT NULL,
"ID_PERSONNEL"   INTEGER       NOT NULL,

CONSTRAINT "RENDEZ_VOUS_PK" PRIMARY KEY ("ID_RENDEZ_VOUS"),

CONSTRAINT "PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE")
REFERENCES "PATIENTE" ("ID_PATIENTE"),
   
CONSTRAINT "PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL")
REFERENCES "PERSONNEL" ("ID_PERSONNEL"),
   
CONSTRAINT "chk_date_rdv" CHECK ("DATE_RDV" >= CURRENT_DATE)
);

         -------------/TABLE CONST_PHYSIOLOGIQUE/---------------

CREATE TABLE "CONST_PHYSIOLOGIQUE" (
"ID_CONST_PHYSIO"      SERIAL          NOT NULL,
"TENSION_ARTERIELLE"   VARCHAR(20),
"POULS"                INTEGER         CHECK ("POULS" BETWEEN 30 AND 250),
"TEMPERATURE"          DECIMAL(4,1)    CHECK ("TEMPERATURE" BETWEEN 30 AND 45),
"TAILLE"               DECIMAL(5,2)    CHECK ("TAILLE" BETWEEN 50 AND 250),
"POIDS"                DECIMAL(5,2)    CHECK ("POIDS" BETWEEN 20 AND 200),
"FREQUENCE_CARDIAQUE"  INTEGER         CHECK ("FREQUENCE_CARDIAQUE" BETWEEN 30 AND 250),
"ANTECEDENTS_CARD"     TEXT,
"DATE_MESURE"          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
"ID_CONSULTATION"      INTEGER         NOT NULL,
"ID_PATIENTE"          INTEGER         NOT NULL,

CONSTRAINT "CONST_PHYSIO_PK" PRIMARY KEY ("ID_CONST_PHYSIO"),

CONSTRAINT "CONSULTATION_FK" FOREIGN KEY ("ID_CONSULTATION")
REFERENCES "CONSULTATION" ("ID_CONSULTATION"),
  
CONSTRAINT "PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE")
REFERENCES "PATIENTE" ("ID_PATIENTE")
);

               -----------/TABLE SYMPTOME/--------------------

CREATE TYPE "NIVEAU_SYMPTOME" AS ENUM ('Faible','Modéré','Critique');

CREATE TABLE "SYMPTOME" (
"ID_SYMPTOME"   SERIAL            NOT NULL,
"NOM"           VARCHAR(100)      NOT NULL UNIQUE,
"DESCRIPTION"   TEXT,
"NIVEAU_SYMPTOME"        "NIVEAU_SYMPTOME" NOT NULL DEFAULT 'Modéré',
CONSTRAINT "SYMPTOME_PK" PRIMARY KEY ("ID_SYMPTOME")
);


                 --------------/TABLE CONSULTATION_SYMPTOME/------------------

CREATE TABLE "CONSULTATION_SYMPTOME" (

"ID_CONSULTATION" INTEGER NOT NULL,
"ID_SYMPTOME" INTEGER NOT NULL,


CONSTRAINT "CONSULTATION_FK" FOREIGN KEY ("ID_CONSULTATION")
REFERENCES "CONSULTATION" ("ID_CONSULTATION"),

CONSTRAINT "SYMPTOME_FK" FOREIGN KEY ("ID_SYMPTOME")
REFERENCES "SYMPTOME" ("ID_SYMPTOME")
);


            ---------------/TABLE DOCUMENT/---------------------

CREATE TYPE "TYPE_DOCUMENT" AS ENUM ('Echographie','Bilan sanguin','Ordonnance','Compte rendu','Autre');

CREATE TABLE "DOCUMENT" (
"ID_DOCUMENT"   SERIAL          NOT NULL,
"TYPE_DOCUMENT" "TYPE_DOCUMENT" NOT NULL,
"NOM_DOCUMENT"  VARCHAR(255)    NOT NULL,
"CONTENU"       TEXT,
"TYPE_MIME"     VARCHAR(50)     NOT NULL
CHECK ("TYPE_MIME" IN ('image/jpeg', 'image/png', 'application/pdf')),
"DATE_DEPOT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
"TAILLE"   INTEGER CHECK ("TAILLE" > 0),
"ID_PATIENTE"   INTEGER         NOT NULL,
"ID_PERSONNEL"  INTEGER,
 
CONSTRAINT "DOCUMENT_PK" PRIMARY KEY ("ID_DOCUMENT"),

CONSTRAINT "PATIENTE_FK" FOREIGN KEY ("ID_PATIENTE")
REFERENCES "PATIENTE" ("ID_PATIENTE"),
   
CONSTRAINT "PERSONNEL_FK" FOREIGN KEY ("ID_PERSONNEL")
REFERENCES "PERSONNEL" ("ID_PERSONNEL")
);


